---
services:

  init:
    container_name: init
    image: systeminit/init:${SI_VERSION}
    profiles: [rebaser, pinga, sdf, veritech]
    environment:
      - SI_HOSTENV=${SI_HOSTENV}
      - SI_SERVICE=${SI_SERVICE}
    volumes:
      - config:/config
      - /etc/${SI_SERVICE}:/service

  otelcol:
    container_name: otelcol
    image: systeminit/otelcol:${SI_VERSION}
    profiles: [rebaser, pinga, sdf, veritech]
    ports:
      - 4317:4317
      - 55679:55679
    volumes:
      - config:/etc/otelcol/
    depends_on:
      init:
        condition: service_completed_successfully

  node-exporter:
    container_name: node_exporter
    image: prom/node-exporter:v1.7.0
    profiles: [rebaser, pinga, sdf, veritech]
    command:
      - --collector.systemd
      - --collector.systemd.unit-include=${SI_SERVICE}.service
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  pgbouncer:
    container_name: pgbouncer
    image: edoburu/pgbouncer:1.22.0-p0
    profiles: [pinga, sdf]
    ports:
      - 5432:5432
    volumes:
      - config:/etc/pgbouncer/
    depends_on:
      init:
        condition: service_completed_successfully

  vector:
    container_name: vector
    image: timberio/vector:0.X-debian
    profiles: [rebaser, pinga, sdf, veritech]
    ports:
      - 8686:8686
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/journal:/var/log/journal
      - config:/etc/vector/
    depends_on:
      init:
        condition: service_completed_successfully

volumes:
  config:
