---
packages:
  - app/auth-portal
  - app/web
  - app/docs
  - bin/auth-api
  - bin/lang-js
  - lib/eslint-config
  - lib/ts-lib
  - lib/ts-lib-deno
  - lib/tsconfig
  - lib/vue-lib
  - lib/yjs-codemirror-plugin
