[package]
name = "pinga"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "pinga"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
pinga-server = { path = "../../lib/pinga-server" }
telemetry-application = { path = "../../lib/telemetry-application-rs" }
tokio = { workspace = true }
