---
version: "3"

services:
# This is the one that will run the remainder of the stack (rust services + web)
  application-services:
    image: systeminit/ci-base:20240404.202200.0-sha.0df5bde58_dirty-dirty-amd64
    command:
      - "tilt"
      - "up"
      - "--file"
      - ".ci/Tiltfile.e2e"
      - "--stream"
    privileged: true
    environment:
      - "SI_TEST_PG_HOSTNAME=postgres"
      - "SI_TEST_PG_PORT=5432"
      - "SI_TEST_NATS_URL=nats"
      - "OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317"
    working_dir: /workdir
    ports:
      - 10350:10350
    volumes:
      - ../.:/workdir
      - /workdir/buck-out
      - /workdir/target
      - /workdir/tmp
    networks:
      - e2e-test

networks:
  e2e-test:
    driver: bridge