[package]
name = "gen-var-defs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
async-trait = { workspace = true }
clap = { workspace = true }
color-eyre = { workspace = true }
convert_case = "0.6.0"
dal = { path = "../../lib/dal" }
derive_builder = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
si-data-nats = { path = "../../lib/si-data-nats" }
si-data-pg = { path = "../../lib/si-data-pg" }
si-settings = { path = "../../lib/si-settings" }
telemetry-application = { path = "../../lib/telemetry-application-rs" }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { version = "1.1.2", features = ["serde", "v4"] }
veritech-client = { path = "../../lib/veritech-client" }
