[package]
name = "council"
version = "0.1.0"
edition = "2021"
rust-version = "1.64"
publish = false

[[bin]]
name = "council"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
council-server = { path = "../../lib/council-server" }
si-service = { path = "../../lib/si-service" }
si-std = { path = "../../lib/si-std" }
