[package]
name = "veritech"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "veritech"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
telemetry-application = { path = "../../lib/telemetry-application-rs" }
tokio = { workspace = true }
veritech-server = { path = "../../lib/veritech-server" }
