[package]
name = "cyclone"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "cyclone"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
cyclone-server = { path = "../../lib/cyclone-server" }
telemetry-application = { path = "../../lib/telemetry-application-rs" }
tokio = { workspace = true }
