name: Crons

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

# We want to ensure that in-progress cron runs are canceled
# when do a deploy so they don't fail erroneously, but these
# cannot cancel deploys
concurrency:
  group: e2e-tools
  cancel-in-progress: false

jobs:
  e2e-validation:
    uses: ./.github/workflows/e2e-validation.yml
    with:
      environment: production
    secrets: inherit
  api-test:
    uses: ./.github/workflows/run-api-test.yml
    with:
      environment: production
    secrets: inherit
